config/routes.rb
Event::Application.routes.draw do
  get "home/index"
  resources :articles
  resources :isfit_events do
    get :on_date, on: :collection
  end
  root :to => 'home#index'
end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :body, :title
end

app/models/isfit_event.rb
class IsfitEvent < ActiveRecord::Base
  attr_accessible :date, :description, :location, :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @article = Article.new
  end

  def create

  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/isfit_events_controller.rb
class IsfitEventsController < ApplicationController
  def new
    @isfit_event = IsfitEvent.new
  end

  def index
    if params[:month] && params[:year]
      @start_date = Date.new(params[:year].to_i, params[:month].to_i)
      @end_date = Date.new(params[:year].to_i, params[:month].to_i,-1)
    else
      @start_date = Date.today.beginning_of_month
      @end_date = Date.today.end_of_month
    end
    @range = @start_date..@end_date
  end

  def on_date
    range = Date.new(params[:year].to_i, params[:month].to_i, params[:day].to_i).beginning_of_day..Date.new(params[:year].to_i, params[:month].to_i,params[:day].to_i).end_of_day
    @isfit_events = IsfitEvent.where(start_date: range)
  end

  def show

  end

  def create
    @isfit_event = IsfitEvent.new(params[:isfit_event])
    if @isfit_event.save
      redirect_to isfit_events_path, notice: "New event created"
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/isfit_events_helper.rb
module IsfitEventsHelper
  def create_calender_start_padding(date)
    unless date.monday?
      if @start_date.sunday?
        start = 6
      else
        start = @start_date.wday - 1
      end
      "<tr>" +
      (1..start).map do
        "<td></td>"
      end.join
    end.try(:html_safe)
  end

  def create_calender_end_padding(date)
    unless date.sunday?
      (@end_date.wday..6).map do
        "<td></td>"
      end.join +
      "</tr>"
    end.try(:html_safe)
  end
end

app/views/articles/_form.html.erb
<%= simple_form_for @article do |f| %>
    <%= f.input :title %>
    <%= f.input :body %>
    <%= f.submit %>
<% end %>

app/views/articles/index.html.erb
<div id="article_form">
  <!-- render form her -->
</div>

<div id="articles">
  <!-- List nye artikler dynamisk (ajax) her -->
</div>

app/views/home/index.html.erb
<%= link_to "Get funny things", "home/index", remote: true %>

app/views/isfit_events/_form.html.erb
<%= simple_form_for @isfit_event, html: {class: 'form-horizontal'} do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :location %>
    <%= f.input :start_date %>
    <%= f.submit %>
<% end %>

app/views/isfit_events/index.html.erb
<h1>Events for <%= Date::MONTHNAMES[@start_date.month] %> <%= @start_date.year %></h1>
<div class="calender_wrapper">
  <nav>
    <%= link_to "<< Previous month", isfit_events_path(month: @start_date.prev_month.month, year: @start_date.prev_month.year) %>
    <%= link_to "Next month >>", isfit_events_path(month: @start_date.next_month.month, year: @start_date.next_month.year), class: "pull-right" %>
  </nav>
  <table class="table">
    <thead>
    <tr>
      <% I18n.t('date.abbr_day_names').each do |day|  %>
          <td><%= day %></td>
      <% end  %>
    </tr>
    </thead>
    <tbody>
    <%= create_calender_start_padding(@start_date) %>

    <% @range.each do |date| %>
        <%= raw "<tr>" if date.monday? %>
        <td><%=link_to date.day, on_date_isfit_events_path(month: date.month, year: date.year, day: date.day) %></td>
        <%= raw "</tr>" if date.sunday? %>
    <% end %>

    <%= create_calender_end_padding(@end_date) %>
    </tbody>
  </table>
</div>
<%= link_to "New event", new_isfit_event_path %>

app/views/isfit_events/new.html.erb
<%= render 'form' %>

app/views/isfit_events/on_date.html.erb
<table class="table">
  <thead>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Location</th>
    <th>Start date</th>
  </tr>
  </thead>
  <tbody>

  <% @isfit_events.each do |isfit_event| %>
    <tr>
      <td><%= isfit_event.title %></td>
      <td><%= isfit_event.description %></td>
      <td><%= isfit_event.location %></td>
      <td><%= isfit_event.start_date %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/isfit_events/show.html.erb
<h1>IsfitEvents#show</h1>
<p>Find me in app/views/isfit_events/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Event</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="notification"></div>

  <div id="main">
    <%= yield %>
  </div>
</body>
</html>